> ### **Assignment 2 - Numpy Array Operations** 



# 5 Useful Function For Beginners


### Numpy

Numpy is a python library used for working with array. It is an easy way to compute large array based data efficiently. Numpy also can be used to work with linear algebra, matrix operation, and any advance math operation and Numpy Array are 50x faster and efficient than python list.

- np.random.randint
- np.arange
- np.reshape
- np.max
- np.argmax

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [20]:
!pip install jovian --upgrade -q

In [43]:
import jovian

In [44]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Creating a new project "sadirga/numpy-array-operations"
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/sadirga/numpy-array-operations


'https://jovian.ml/sadirga/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [3]:
import numpy as np

 List of functions explained 
>##### function1 = np.random.randint
>##### function2 = np.arange
>##### function3 = np.reshape
>##### function4 = np.max
>##### function5 = np.argmax

## Function 1 - np.random.randint

To get a random integer value in an array

In [28]:
# Example 1 - 1 parameter
arr1 = np.random.randint(10)
arr1

0

In [ ]:
?np.random.randint


As you can see, if we call np.random.randint(n) it will return a number from range 0 - 9, just like python function

In [33]:
# Example 2 - 2 parameters
np.random.randint(11,30)

16

If you put 2 parameters on the method, it will return an random integer value, start from the low (1st parameter) and end in high (2nd parameter)

In [41]:
# Example 3 - breaking (to illustrate when it breaks)
print(np.random.randint(11,100,20))
np.random.randint()
np.random.randint(100,11,10)

[98 66 40 51 45 87 55 70 32 99 55 97 20 88 14 44 82 61 34 68]


TypeError: randint() takes at least 1 positional argument (0 given)

- you could also set on how much element did you want on the array, the 1st parameter is the lowest range of int value, the 2nd is the highest(not included) range of int value and the 3rd parameter is total element in the array
- You should input a number whenever you use this function
- The 1st parameter is always the lowest number and the 2nd parameter is the highest else it will show you an error

this function quite useful if you need sample number to exercise or just to create a sample

In [45]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "sadirga/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/sadirga/numpy-array-operations


'https://jovian.ml/sadirga/numpy-array-operations'

## Function 2 - np.arange

#To build a an array just like a range in python list

In [49]:
# Example 1 - working
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

as mentioned above, arange in numpy is similar to range in python. if you input an int value on parameter, it will create a sequence of list/array from 0 to the input value - 1

In [50]:
# Example 2 - working
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

By putting the 2nd and 3rd parameter value, it will create a sequence of list with range starts from the 1st parameter, ends in 2nd parameter and the 3rd parameter is the increment value.
Increment value is The process of increasing or decreasing a numeric value by another value. if you put 2 and arange starts from 1 then the next number would be 3, skipping the number 2

In [59]:
# Example 3 - breaking (to illustrate when it breaks)
np.arange(10,1)

array([], dtype=int32)

If you want to create a sequence of number with descending order, you must include the increment -1. If you not put - increment it will not working

this function quite useful if you need sample number to exercise or just to create a sample

In [32]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-array-operations


'https://jovian.ml/aakashns/numpy-array-operations'

## Function 3 - np.reshape

To change the shape of an array

In [67]:
# Example 1 - working
my_list = [[
        [ 1,  2,  3, 28],
        [ 4,  5,  6, 29],
        [ 7,  8,  9, 30]],

       [[10, 11, 12, 31],
        [13, 14, 15, 32],
        [16, 17, 18, 33]],

       [[19, 20, 21, 34],
        [22, 23, 24, 35],
        [25, 26, 27, 36]]]
array_3d = np.array(my_list)
array_3d.reshape(-1)

array([ 1,  2,  3, 28,  4,  5,  6, 29,  7,  8,  9, 30, 10, 11, 12, 31, 13,
       14, 15, 32, 16, 17, 18, 33, 19, 20, 21, 34, 22, 23, 24, 35, 25, 26,
       27, 36])

As seen from the sample above, by giving a -1 value, it will change the array_3D shape from 3D into 1D/vector

In [78]:
# Example 2 - working
print((array_3d.reshape(-1).shape),"\n")
print(array_3d.reshape(6,6))
array_3d.reshape(2,3,6)

(36,) 

[[ 1  2  3 28  4  5]
 [ 6 29  7  8  9 30]
 [10 11 12 31 13 14]
 [15 32 16 17 18 33]
 [19 20 21 34 22 23]
 [24 35 25 26 27 36]]


array([[[ 1,  2,  3, 28,  4,  5],
        [ 6, 29,  7,  8,  9, 30],
        [10, 11, 12, 31, 13, 14]],

       [[15, 32, 16, 17, 18, 33],
        [19, 20, 21, 34, 22, 23],
        [24, 35, 25, 26, 27, 36]]])

We could also change it into 2D/matrix or any other shape by checking the total of element first by using `.shape` just like the sample above and the you reshape with m * n = total element of array_3d. you could also shape it back into 3D with this calculation in mind (m * n * t = total element of an array)

In [79]:
# Example 3 - breaking (to illustrate when it breaks)
array_3d.reshape(2,2,4)

ValueError: cannot reshape array of size 36 into shape (2,2,4)

It will show you an error if you put the int value as parameter without making calculation m * n = total element. if the total element of an array is 36, then you when you want to reshape it into 3D array then you can put (3,2,6)/(6,6,1) or if you want it reshape it into 2D array it should be (6,6)/(18,2)/(36,1)

This function very useful if you have a data that need to be reshape to match your calculation

In [80]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "sadirga/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/sadirga/numpy-array-operations


'https://jovian.ml/sadirga/numpy-array-operations'

## Function 4 - np.max

Array attributes and methods

In [93]:
# Example 1 - working
arra = np.random.randint(1,100,10)
arra

array([61, 80, 22,  9, 91, 60, 77, 57,  3, 34])

In [90]:
np.max(arra)

54

It as simple as finding the highest number in an array

In [96]:
# Example 2 - working
arra1 = np.arange(10,1,-1)
arra1.max()

10

np.max could also be run by calling the variable name of an array first then `.max()`

In [95]:
# Example 3 - breaking (to illustrate when it breaks)
arra.max(1)

AxisError: axis 1 is out of bounds for array of dimension 1

np.max does not need a parameter to run. Just simply give an empty parantheses

This function very usefule if you want to find, let's say the biggest salary in your data

## Function 5 - np.argmax

Array attributes and methods

In [211]:
# Example 1 - working
arra = np.random.randint(1,100,10)
arra

array([47, 44, 25, 36, 94, 56, 78, 27, 96, 47])

In [195]:
arra.argmax()

3

This function will show you the index of the biggest value in an array

In [212]:
# Example 2 - working
arra2 = arra.reshape(2,5)
arra2

array([[47, 44, 25, 36, 94],
       [56, 78, 27, 96, 47]])

In [214]:
arra2.argmax(1)

array([4, 3], dtype=int64)

In [215]:
arra2.shape

(2, 5)

When your array has shape of 2D you can input a parameter of 1 to show the index of the biggest value on each row and also it shows its `.datatype`

In [213]:
# Example 3 - breaking (to illustrate when it breaks)
arra2.argmax(0)

array([1, 1, 1, 1, 0], dtype=int64)

when your array is 2D, and you put 0 on the int value in `argmax()`, it will show you which index on each element between rows (in this case we have 2 rows) that has the bigger value.

This function will be helpful to give the information on which index has the biggest value or you can compare between 2 outer row which has the bigger value

In [171]:
?np.argmax

In [216]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "sadirga/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/sadirga/numpy-array-operations


'https://jovian.ml/sadirga/numpy-array-operations'

## Conclusion

Those are the 5 Useful Function to begin with as a beginner in the numpy as an introduction

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [217]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "sadirga/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/sadirga/numpy-array-operations


'https://jovian.ml/sadirga/numpy-array-operations'